version: '3.7'

services:
# nginx section (web server)
  nginx:
    container_name: laravel-nginx
    image: nginx
    ports:
      - "80:80"
      - "4443:443"
    links:
      - fpm
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf
    working_dir:
      /var/www

# php section
  fpm:
    container_name: laravel-fpm
    build: docker/php74
    links:
      - db
    volumes:
      - ./:/var/www/laravel
    working_dir:
      /var/www/laravel
#db section
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    container_name: laraveldb
    ports:
      - 3307:3306